name: ci/cd pipeline actions

on: #event that triggers the workflow.
  push: #whenever code is pushed to the repository.
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3  #Pulls your code from GitHub into the runner so the workflow can access it.
      - name: Setup Java
        uses: actions/setup-java@v3 #Installs Java 21 using Temurin distribution on the runner.
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build project
        run: mvn clean install -DskipTests  # Runs Maven commands to compile your Java code and generate a JAR file.
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4 #Saves the built JAR as an artifact so other jobs (like deploy) can use it.
        with: #artifact is basically a file or set of files produced by a build
          name: dockerdemo
          path: ${{ github.workspace }}/target/*.jar  #above build jar file stored here for 90 days

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dockerdemo # names must match upload/download
      - name: Deploying to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: PRACTISEAPP1
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: '*.jar'
#      - name: Configure Azure App Settings
#        uses: azure/appservice-settings@v1
#        with:
#          app-name: PRACTISEAPP1
#          app-settings-json: |
#            [
#              { "name": "DB_HOST", "value": "${{ secrets.DB_HOST }}" },
#              { "name": "DB_NAME", "value": "${{ secrets.DB_NAME }}" },
#              { "name": "DB_USERNAME", "value": "${{ secrets.DB_USERNAME }}" },
#              { "name": "DB_PASSWORD", "value": "${{ secrets.DB_PASSWORD }}" }
#            ]
  
  

  #https://www.youtube.com/watch?v=WcXt_UONkz4 (above code video)
  # https://www.youtube.com/watch?v=ly2a9Pnl1xw (issue in downloading publish profile in azure)